name: emecexpo
description: "A new Flutter project."
# يمنع نشر الحزمة على pub.dev
publish_to: 'none'

# تم تحديث رقم الإصدار (Build Number) ليكون جاهزاً للرفع الجديد
version: 1.0.0+28

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  intl: any
  font_awesome_flutter: any
  carousel_slider: any
  flutter_staggered_grid_view: any

  # --- تم حذف مكتبات WebView نهائياً لحل مشكلة الرفض من Apple ---
  # المكتبات المحذوفة: webview_flutter, webview_flutter_android, webview_flutter_wkwebview

  badges: any
  app_badge_plus: any
  permission_handler: any
  flutter_carousel_slider: any
  flutter_svg:
  flutter_easyloading: any
  http: any
  flutter_native_splash: any
  shared_preferences: any
  animate_do: any
  csv:
  googleapis_auth: any
  flutter_animate: any
  mobile_scanner: ^7.1.3
  fluttertoast: any
  timezone: any
  connectivity_plus:
  rxdart: any
  get: any
  file_picker: any
  app_settings: any

  # المكتبة الأساسية لفتح الروابط في المتصفح الخارجي
  url_launcher: ^6.3.0

  sqflite: any
  google_maps_flutter:
  geocoding:
  cached_network_image:
  provider: any
  equatable: any
  flutter_launcher_icons: any
  path_provider: any
  add_2_calendar: any
  change_app_package_name:
  googleapis: any
  animated_splash_screen: any

flutter_native_splash:
  image: assets/logo15.png
  color: "#261350"
  android_gravity: center

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/ICON-EMEC.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  material_color_utilities: any
  meta: any
  permission_handler_android: any
  test_api: any

flutter:
  uses-material-design: true

  # الأصول (Assets) الخاصة بمشروع emecexpo
  assets:
    - assets/
    - assets/partners/
    - assets/sponsors/
    - assets/slides/
    - assets/sponsors/sponsors2023/
    - assets/sponsors/sponsors2024/
    - assets/sponsors/sponsors2024/Bronze/
    - assets/sponsors/sponsors2024/Gold/
    - assets/sponsors/sponsors2024/platinum/
    - assets/sponsors/sponsors2024/StrategicPartner/
    - assets/speakers/
    - assets/Comercials/
    - assets/speakers/speakers2024/
    - assets/Comercials/Comercials2024/
    - assets/safety/
    - assets/service_account.json
    - assets/icons/